import { ListProducts } from "../routes/product.routes";

export const listProducts: ListProducts[] = [
  {
    product_id: 2289,
    product_name: "BOIA ABC",
    price: "20.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(95)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><p>Desejamos boas compras !!<br></p><h3>#vemfofoconhecer</h3><p><br></p><p>- Boia Inflável Redonda 90cm - Diversão Garantida para Piscina e Praia ! <br>- Transforme seus momentos de lazer com a Boia Inflável Redonda de 90cm , ideal para crianças e adultos ! Feita com material resistente e durável ,&nbsp;&nbsp; essa boia é perfeita para curtir dias ensolarados na piscina ou na praia com segurança e conforto . Seu design ergonômico e leve facilita o transporte e o enchimento , garantindo praticidade no dia a dia . <br>- Com 90 cm de diâmetro , oferece estabilidade na água e é indicada para <br></p><p>- Diâmetro : 90 cm <br>- Material : PVC resistente e de alta qualidade <br>-Uso : Piscina e Praia Indicado para : Crianças&nbsp; +3 e&nbsp; Adultos Fácil de inflar e transportar<br>- seus dias de sol com mais diversão e segurança ! <br></p><p>- COR AMARELO&nbsp; COM AZUL.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(94)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(92)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(95)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2294,
    product_name: "BOIA COLETE",
    price: "11.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(20)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!</h4><h3>#vemfofoconhecer<br></h3><p>-&nbsp; Colete Inflável Boia para Piscina Praia Lago Infantil Flutuador Salva Vidas para Criança e&nbsp; Unissex M<br>Com a chegada do verão , as crianças costumam se divertir em praias e piscinas e nada melhor do que aliar a diversão à segurança . Com os coletes infláveis , você tem uma segurança a mais na hora da diversão do seu pequeno .&nbsp;</p><p>-O Colete possui apoio flutuador para a cabeça evitando que a criança vire e fazendo com que a cabeça permaneça fora da água . <br>- RECOMENDAÇÕES : Lembrando que as crianças sempre devem estar sob a supervisão de um adulto na hora de entrar na água , nunca devendo entrar sozinha . Evite que a criança fique perto de objetos pontiagudos ou cortantes para que o colete não venha a rasgar ou esvaziar .&nbsp;&nbsp;</p><p>- Conteúdo : 01 colete inflável com alças reguláveis - Material : Plástico PVC de alta qualidade.<br>TAMANHOS Médio ( 6 a 8) : 60 cm x 45 cm ( suporta de 20 a 35 kg ) - <br><br></p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(20)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(23)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(21)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(22)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2324,
    product_name: " BOIA SIMPLES",
    price: "9.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(36)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer</h3><p><br></p><p>-Tendências 1 Peça Boia Inflável Listrada Retrô Para Natação , Aro Flutuante Espesso Para Debaixo Dos Braços , Boia Salva - Vidas , Essencial Para Praia Ao Ar Livre , Aprimora A Diversão Aquática De Verão !</p><p>-Especificações : Material da Embalagem : PVC&nbsp; </p><p>-O pacote de inclui : <br>Brinquedo Brinquedo de Brinquedo * 1</p><p>- 70 CM # ( adequado para 7-10 anos ) .</p><p>-COR AZUL E ROSA&nbsp;</p><p> - recomendado para crianças + 5 ano com supervisão de um adulto.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(36)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(34)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(32)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-11 at 15.21.22(2)-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(35)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2342,
    product_name: "BOIA TRANSPARENTE",
    price: "9.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(39)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><p><br></p><h4>Desejamos boas compras !!</h4><p><br></p><h3>#vemfofoconhecer</h3><p><br>-Tendências 1 Peça Boia Inflável Retrô Para Natação , Aro Flutuante Espesso Para Debaixo Dos Braços , Boia Salva - Vidas , Essencial Para Praia Ao Ar Livre , Aprimora A Diversão Aquática De Verão !</p><p>-90cm # ( para adultos )&nbsp;</p><p>-Especificações : Material da Embalagem : PVC <br>-O pacote de inclui :2 boia transparente&nbsp; estampada com trevos na cor verde .</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(37)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(38)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(39)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2345,
    product_name: " BOIA TRANSPARENTE C/ FLORES",
    price: "9.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(43)-150x150.jpg",
    video: null,
    description:
      '<p><span style="color: inherit; font-family: inherit; font-size: 23px;">Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</span></p><p><br></p><h4>Desejamos boas compras !!<br></h4><p><br></p><h3>#vemfofoconhecer!!</h3><p><br>-Tendências\r\n 1 Peça Boia Inflável Retrô Para Natação , Aro Flutuante Espesso Para \r\nDebaixo Dos Braços , Boia Salva - Vidas , Essencial Para Praia Ao Ar \r\nLivre , Aprimora A Diversão Aquática De Verão !</p><p>-RECOMENDAÇÕES : Lembrando que as crianças sempre devem estar sob a supervisão de um adulto na hora de entrar na água , nunca devendo entrar sozinha . Evite que a criança fique perto de objetos pontiagudos ou cortantes para que o boia não venha a rasgar ou esvaziar .&nbsp; <br></p><p>-70cm # ( +4 anos ) <br></p><p>-Especificações : Material da Embalagem : PVC <br>-O pacote de inclui :2 boia transparente&nbsp; estampada com&nbsp; flor margarida na cor branca.</p><p><br></p>',
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(42)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(41)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(40)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(43)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2450,
    product_name: "CADERNOS 1 MAT",
    price: "24.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(154)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!!</h3><p><br><br>- Está buscando um caderno versátil e prático para organizar suas anotações? O Caderno Smart&nbsp; é a escolha ideal! Com design<br>compacto e funcional, ele é perfeito para acompanhar você em todas as suas atividades diárias, seja no trabalho, na escola ou em casa<br>- Detalhes do produto:<br>&nbsp; Quantidade: 1 unidade<br><br>- utilidade: Anotações, organização, estudos, planejamento</p><p>-Estampas variadas de acordo com a imagens e o ESTOQUE!.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(155)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(154)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(153)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2467,
    product_name: "CADERNOS DIVERSOS 1 MAT",
    price: "24.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-31 at 11.59.00-150x150.jpeg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!!</h3><p><br><br>- Está buscando um caderno versátil e prático para organizar suas anotações? O Caderno Smart&nbsp; é a escolha ideal! Com design compacto e funcional, ele é perfeito para acompanhar você em todas as suas atividades diárias, seja no trabalho, na escola ou em casa<br>- DETALHES DO PRODUTO ESTAMPAS VARIADAS <br>&nbsp;- Quantidade: 1 unidade.<br><br>- utilidade: Anotações, organização, estudos, planejamento.</p><p>- Estampas variadas de acordo com a imagens e&nbsp; estoque!.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-31 at 12.00.29-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 11.54.32-350x350.jpeg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2470,
    product_name: "CADERNO FLORES 1 MATERIA",
    price: "24.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-04-16 at 09.01.18-150x150.jpeg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!!</h3><p><br>- Está buscando um caderno versátil e prático para organizar suas anotações? O Caderno Smart&nbsp; é a escolha ideal! Com design<br>compacto e funcional, ele é perfeito para acompanhar você em todas as suas atividades diárias, seja no trabalho, na escola ou em casa<br>- Detalhes do produto: ESTAMPA FLORIDAS&nbsp; BELÍSSIMAS .<br>&nbsp; Quantidade: 1 unidade<br>- utilidade: Anotações, organização, estudos, planejamento</p><p>-Estampas variadas de acordo com a imagens e o Estoque.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-04-16 at 09.01.18-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(163)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(162)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(165)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2473,
    product_name: "CADERNOS DIVERSOS 1 MAT",
    price: "24.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 15.06.37-150x150.jpeg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!!</h3><p>- Está buscando um caderno versátil e prático para organizar suas anotações? O Caderno Smart&nbsp; é a escolha ideal! Com design<br>compacto e funcional, ele é perfeito para acompanhar você em todas as suas atividades diárias, seja no trabalho, na escola ou em casa<br>- ESTAMPADO COM PLANETA E ESTRELA.<br>-&nbsp; Quantidade: 1 unidade <br>- utilidade: Anotações, organização, estudos, planejamento FOLHA A4.</p><p>-Estampas variadas de acordo com a imagens e o Estoque!&nbsp; COR VERDE,ROXO, AZUL E SALMÃO.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 15.06.37-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 14.47.35-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 14.44.22-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 14.43.41-350x350.jpeg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2475,
    product_name: "CADERNOS DIVERSOS 1 MAT",
    price: "24.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 15.13.02-150x150.jpeg",
    video: null,
    description:
      '<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!!</h3><p><br>- Está buscando um caderno versátil e prático para organizar suas anotações? O Caderno Smart&nbsp; é a escolha ideal! Com design<br>compacto e funcional, ele é perfeito para acompanhar você em todas as suas atividades diárias, seja no trabalho, na escola ou em casa<br>- DETALHES DO PRODUTO <a href="produto:CADERNOS">: CADERNOS</a>&nbsp; COLORIDOS CHEIO DE PERSONALIDADES.<br>-&nbsp; Quantidade: 1 unidade<br>- utilidade: Anotações, organização, estudos, planejamento.</p><p>-Estampas variadas de acordo com a imagens e o Estoque!ROSA&nbsp; ROXO VERDE E AZUL.</p>',
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 15.12.28-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 15.11.49-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 15.13.28-350x350.jpeg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2478,
    product_name: " CADERNOS VARIADOS SPACE",
    price: "24.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(56)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!!</h3><p>- Está buscando um caderno versátil e prático para organizar suas anotações? O Caderno Smart&nbsp; é a escolha ideal! Com design<br>compacto e funcional, ele é perfeito para acompanhar você em todas as suas atividades diárias, seja no trabalho, na escola ou em casa<br>- Detalhes do produto: CADERNO MEGA COLORIDO SUPER DIVERTIDO&nbsp; ESTAMPADO.<br>&nbsp; Quantidade: 1 unidade<br>- utilidade: Anotações, organização, estudos, planejamento</p><p>-Estampas variadas de acordo com a imagens e o Estoque! COLORIDO .</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-14 at 15.43.20-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(56)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-04-14 at 08.49.13-350x350.jpeg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2488,
    product_name: "CADERNOS VARIADOS",
    price: "24.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(151)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><p><br></p><h4>Desejamos boas compras !!</h4><p><br></p><h3>#vemfofoconhecer!!</h3><p><br></p><p>- Está buscando um caderno versátil e prático para organizar suas anotações? O Caderno Smart&nbsp; é a escolha ideal! Com design<br>compacto e funcional, ele é perfeito para acompanhar você em todas as suas atividades diárias, seja no trabalho, na escola ou em casa<br>- Detalhes do produto: caderno estampado com árvore flores e folhas.<br>- Quantidade: 1 unidade<br>- utilidade: Anotações, organização, estudos, planejamento<br>- Estampas variadas de acordo com a imagens e o Estoque!.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-15 at 08.18.57-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(157)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2493,
    product_name: " CADERNOS VARIADOS",
    price: "24.9900",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(53)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><p><br></p><h4>Desejamos boas compras !!</h4><p><br></p><h3>#vemfofoconhecer!</h3><p><br></p><p>- Está buscando um caderno versátil e prático para organizar suas anotações? O Caderno Smart&nbsp; é a escolha ideal! Com design<br>compacto e funcional, ele é perfeito para acompanhar você em todas as suas atividades diárias, seja no trabalho, na escola ou em casa<br>- Detalhes do produto: CADERNO ESTAMPADO COM DESENHOS DE MORANGO SUPER FOFO.<br>&nbsp; -Quantidade: 1 unidade<br>- utilidade: Anotações, organização, estudos, planejamento<br>Estampas variadas de acordo com a imagens e o Estoque COR ROSA .</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(53)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(52)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-15 at 09.06.19-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(55)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2528,
    product_name: "ESCAVADEIRA QUE SOLTA FUMAÇA",
    price: "177.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(143)-150x150.jpg",
    video: null,
    description:
      '<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!!</h3><p>Essa escavadeira de brinquedo é a diversão garantida para qualquer pequeno operador de máquinas! Com design robusto e cores vibrantes, esse trator escavadeira com controle remoto. vai transformar qualquer quintal, sala ou caixa de areia em um verdadeiro canteiro de obras. O mais incrível é que a pá de escavação funciona de verdade, movimentando-se em até 90° para cavar, levantar e mover terra, areia ou qualquer outro "material de construção" que estiver por perto.<br>A escavadeira e o controle remoto são alimentados por pilhas AA (não inclusas), garantindo horas e horas de aventura sem parar! O controle é fácil de manusear, com botões precisos para mover a pá e controlar o trator para frente e para trás. E como se o seu pequeno construtor estivesse no comando de uma máquina de verdade! Pronta para qualquer missão, desde cavar buracos imaginários até criar verdadeiras obras de arte na areia, essa escavadeira vai estimular a criatividade, a coordenação e, claro, proporcionar muita diversão.&nbsp; ideal para crianças que amam o mundo da construção!<br></p>',
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-18 at 08.12.25-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(143)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(142)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-18 at 08.12.25(3)-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(144)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2539,
    product_name: "PRANK SNAKE MIKE",
    price: "74.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/Weixin Image_20250227114357-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!!</h3><p>-Brinquedo Cobra Cascavel Realista - Pegadinha Divertida! Surpreenda seus amigos e familiares com esse brinquedo em forma de cobra cascavel super realista! Feita com materiais de alta qualidade, esse brinquedo imita perfeitamente a aparência de uma serpente de verdade, garantindo sustos e risadas.<br>-&nbsp;&nbsp; PRANK SNAKE MIKE : Jack Rattle snake 1,1 chapéu de cowboy,1 moeda dupla face , PEDRINHAS DE OURO&nbsp; 16<br>- Descrição COMPLETA Devido a diferenças de brilho e exibição, as cores e acabamentos reais podem ser ligeiramente diferentes das exibidas online.<br>-&nbsp; o jogo. Requer 3 pilhas AAA (não incluídas). Disponível a 2 ou mais jogadores de 4 anos ou mais. Rattlesnake Jack roubou o ouro - você pode recuperá-lo? Cuidado com o chocalho dele, observe para que você retire o ouro com cuidado&nbsp; de jogos que as crianças conhecem e amam Um chocalho cria uma enorme suspense!<br>- Necessita de 3 pilhas AAA (não incluída) Disponível a 2 ou mais jogadores com 4 anos ou mais de idade e acima.</p><p>-NA COR VERDE COM AMARELO!.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Weixin Image_20250227114357-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(131)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(128)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(129)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(130)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2562,
    product_name: " CARRO CONTROLE REMOTO ",
    price: "136.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(71)-150x150.jpg",
    video: null,
    description:
      "<p>O que este item contém:<br>-1 Carro<br>-1 Controle remoto 2.4G com 8 canais<br>-1 Cabo de Energia<br>-1 Bateria recarregável 3.7V 500mAh<br>-Características:Tranforma em 540° graus Transforma com um clique no controle remoto,Possui luz e som.<br>-Tamanho do carro: 22x17x16cm<br>-Tempo de trabalho: 30 minutos<br>-Tempo de carregamento: até 90 minutos<br>-Tamanho do pacote: 35*19*21 cm.</p><p>-na cor azul&nbsp; .</p><p>- não recomendado -3 anos.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(69)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(70)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(71)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(72)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2564,
    product_name: " CARRO CONTROLE REMOTO ",
    price: "136.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(73)-150x150.jpg",
    video: null,
    description:
      "<h3>lá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!</h3><p>O que este item contém<br>-1 Carro<br>-1 Controle remoto 2.4G com 8 canais<br>-1 Cabo de Energia<br>-1 Bateria recarregável 3.7V 500mAh<br>-Características:Transforma em 540° graus Transforma com um clique no controle remoto,Possui luz e som<br>-Tamanho do carro: 22x17x16cm<br>-Tempo de trabalho: 30 minutos<br>-Tempo de carregamento: até 90 minutos<br>-Tamanho do pacote: 35*19*21 cm</p><p>-não recomendado para -3 anos.</p><p>-cor amarelo .</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(75)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(74)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(73)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2579,
    product_name: " BOLA DE BASQUETE",
    price: "18.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(49)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer!!</h3><p><br>Eleve o seu jogo com a Bola de basquete, projetada para uso recreativo e competitivo. Seu vibrante tonm&nbsp; não só adiciona estilo, como também melhora a visibilidade durante partidas intensas. superfície de toque suave garante uma pegada confortável, reduzindo o impacto nas mãos e proporcionando controle máximo. Perfeita para todos os níveis de habilidade, esta bola é durável e leve, ideal.<br><br>-BOLA BASQUETE Diâmetro: 24,5cm Composição: Outdoor Peso: 500g,<br>-ATENÇÃ0: temos varias opções de bola, selecionar a que desejar</p><p>-Bola são enviadas murchas por fins de logística.</p>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(49)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(50)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(48)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2626,
    product_name: "MALETA PINTURA UNICORNIO 86 PÇS",
    price: "35.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-22 at 09.45.43(2)-150x150.jpeg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><p><br></p><h4>Desejamos boas compras !!</h4><p><br></p><h3>#vemfofoconhecer</h3><p><br></p><p>Maleta de Desenho Infantil<br>Estimule a criatividade e o aprendizado das crianças com a nossa incrível maleta de pintura. Essa maleta proporciona horas de diversão para pequenos artistas!<br></p><p>ESTOJO KIT DE 86 PEÇAS CONTÉM:<br>24 canetinhas hidrocor<br>12 bastões de giz<br>24 lápis de cor</p><p>1 borracha<br>1 apontador<br>5 clipes<br>1 cola<br>1 pincél<br>1 régua<br>1 paleta<br>1 lápis preto<br>1 esponja<br>12 aquarelas<br>1 tesoura</p><p>COR: AZUL E ROSA.</p><h4>*idade:+4 anos!</h4>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-22 at 09.45.43(2)-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-22 at 09.45.43(1)-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-22 at 09.45.42-350x350.jpeg",
      "image/cache/catalog/seller_upload_id21/WhatsApp Image 2025-03-22 at 09.45.43-350x350.jpeg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
  {
    product_id: 2844,
    product_name: " MALETA DE PINTURA 150 PÇS",
    price: "39.0000",
    main_image:
      "image/cache/catalog/seller_upload_id21/Design sem nome(83)-150x150.jpg",
    video: null,
    description:
      "<h3>Olá sejam bem vindos a FOFO BRINQUEDOS, sua loja de brinquedos favorita do BUSCA BUSCA !! ✨</h3><h4>Desejamos boas compras !!<br></h4><h3>#vemfofoconhecer</h3><p>Kit pintura 150 peças Estojo Maleta Pintura Infantil Canetinhas Giz Lápis Cores e Tamanhos Variados + Desenhos Para Colorir Presente infantil Temos capa AZUL(dinossauro) e ROSA(Unicórnio) para escolher elevar<br>ESTOJO KIT DE 150 Contém:<br>6 papéis para desenho<br>36 canetinhas hidrocor<br>48 bastões de giz <br>24 lápis de cor</p><p>1 borracha<br>1 apontador<br>20 clipes<br>1 cola<br>1 pincél<br>1 régua<br>1 paleta<br>1 grampeador</p><h4>* idade:+4 anos!<br></h4>",
    seller_id: 21,
    images: [
      "image/cache/catalog/seller_upload_id21/Design sem nome(83)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(81)-350x350.jpg",
      "image/cache/catalog/seller_upload_id21/Design sem nome(82)-350x350.jpg",
    ],
    related_products: null,
    options: null,
    is_current: 0,
    payment_methods: null,
    total_records: 243,
    per_page: 20,
    current_page: 2,
    total_pages: 13,
  },
];
